stages:
  - test
  - build
  - deploy
unit-test:
  stage: test
  script: echo 'Testing...'
  tags: 
    - website
yarn-build:
  stage: build
  script: yarn && yarn build
  tags: 
    - website
deploy:
  stage: deploy
  script: echo 'Deploying...'
  tags: 
    - website