stages:
  - test
  - build
  - deploy
unit-test:
  stage: test
  script: echo 'Testing...'
  tags: 
    - website
yarn-build:
  stage: build
  artifacts:
    paths:
    - build/
    expire_in: 1 week
  script:
    - yarn
    - yarn build
  tags: 
    - website
deploy:
  stage: deploy
  script: echo 'Deploying...'
  tags: 
    - website