variables:
  WEBSITE_DIRECTORY: "/Users/justin/Unity/JustinTrotter.github.io"

stages:
  - test
  - build
  - deploy
unit-test:
  stage: test
  only:
    - master
  script: echo 'Testing...'
  tags: 
    - website
yarn-build:
  stage: build
  only:
    - master
  artifacts:
    paths:
    - build/
    expire_in: 1 week
  script:
    - yarn
    - yarn build
  tags: 
    - website
deploy:
  stage: deploy
  only:
    - master
  script: 
    - cp -r ./build/* $WEBSITE_DIRECTORY
    - cd $WEBSITE_DIRECTORY
    - git add -A
    - git commit -m "deploy commit ${CI_COMMIT_SHA:0:8}"
    - git push
  tags: 
    - website